const types = {
  auth: {
    SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: '@auth/SIGN_IN_FAILURE',

    SIGN_UP_REQUEST: '@auth/SIGN_UP_REQUEST',
    SIGN_UP_FAILURE: '@auth/SIGN_UP_FAILURE',

    SIGN_OUT: 'auth/SIGN_OUT',
  },

  user: {
    UPDATE_PROFILE_REQUEST: '@user/UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_SUCCESS: '@user/UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: '@user/UPDATE_PROFILE_FAILURE',
  },
};

export default types;
